global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
#  - job_name: 'otel-collector'
#    static_configs:
#      - targets: ['otel-collector:8889']
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]